### ISSUE TITLE
Able to be embedded in a single executable?

### ISSUE THREAD

**Issue by fire** [BinomialLLC/bc7e#1]
Is bc7e able to be embedded in a single executable and without openmp / ucrt / crt?

I remember ispc not being able to do this 3-4 years ago.

This is for use in Godot Engine.

**Comment by fire** [comment]
Saw ISPC can emit c++.

```
mkdir build
cd build
..\ispc -g -O2 "../bc7e.ispc" -h "bc7e_ispc.h" --target=generic-x64 --opt=disable-assertions --emit-c++ -o "bc7e_ispc.cpp"
```

**Comment by fire** [comment]
1. emit-c++ has been removed from the latest version of ispc
1. emit-llvm requires llc to compile the bitcode
1. emit-asm I couldn't get to work
1. shipping ispc is not a good option
1. requiring developers to use ispc is hard

**Comment by richgel999** [comment]
Your findings are very interesting. I was under the impression that ispc usage is pretty common, even on consoles (surprisingly). (FWIW, we've made license deals off our ispc code.) I have an pure C++ alternative which I could port the ispc code to (cppspmd_fast), which would eliminate ispc completely.

**Comment by fire** [comment]
Wow, thats amazing tell me how it goes.

On Dec 15, 2020, at 5:14 PM, Rich Geldreich <notifications@github.com> wrote:

﻿
Your findings are very interesting. I was under the impression that ispc usage is pretty common, even on consoles (surprisingly). (FWIW, we've made license deals off our ispc code.) I have an pure C++ alternative which I could port the ispc code to (cppspmd_fast), which would eliminate ispc completely.

**Comment by fire** [comment]
@richgel999 Keep me posted about any releases of a SIMD C++ bc7 compressor.

**Comment by fire** [comment]
Thanks I was able to embed this into Godot.

Having trouble investigating why the default is degraded though.

Degraded. Flag 3, perceptual on. INTERPOLATE_LANCZOS (on) is 1.5s, billinear is 0.8s. Trying lod texure bias -2.

![image](https://user-images.githubusercontent.com/32321/106398555-4a887d00-63c8-11eb-82fc-7972e647ecb9.png)

Loss-less

![image](https://user-images.githubusercontent.com/32321/106398566-612ed400-63c8-11eb-9b7a-d192433a4d1d.png)

**Comment by fire** [comment]
Something went horribly wrong.


```
Luma  Max error: 186.000000 RMSE: 11.887165 PSNR 26.629238 dB

RGB   Max error: 190.000000 RMSE: 12.718388 PSNR 26.042162 dB

RGBA  Max error: 190.000000 RMSE: 11.014447 PSNR 27.291550 dB

Alpha Max error: 0.000000 RMSE: 0.000000 PSNR 10000000000.000000 dB

# official encoder
Total time: 0.252000 secs
Total time: 0.090000 secs
Wrote DDS file unpacked_output.png
Luma  Max error:   9 RMSE: 0.485853 PSNR 54.40 dB
RGB   Max error:  24 RMSE: 0.806147 PSNR 50.00 dB
RGBA  Max error:  24 RMSE: 0.765902 PSNR 50.45 dB
Alpha Max error:   1 RMSE: 0.629923 PSNR 52.15 dB
Wrote PNG file clay-banks-ZNUh3gpkt1s-unsplash-crop_unpacked.png
Wrote PNG file clay-banks-ZNUh3gpkt1s-unsplash-crop_unpacked_alpha.png
```

**Comment by fire** [comment]
Resolved https://github.com/fire/godot/tree/bc7e.

64 bit address is not compatible from ispc.
